// js/routes-data.js
const BRAZIL_CAPITALS = [
  'São Paulo',
  'Rio de Janeiro',
  'Brasília',
  'Salvador',
  'Fortaleza',
  'Belo Horizonte',
  'Manaus',
  'Curitiba',
  'Recife',
  'Porto Alegre',
  'Goiânia',
  'Belém',
  'Maceió',
  'Teresina',
  'São Luís',
  'Aracaju',
  'Natal',
  'Campo Grande',
  'Cuiabá',
  'João Pessoa',
  'Boa Vista',
  'Macapá',
  'Palmas',
  'Rio Branco'
];

const CAPITAL_STATES = {
  'São Paulo': 'SP',
  'Rio de Janeiro': 'RJ',
  'Brasília': 'DF',
  'Salvador': 'BA',
  'Fortaleza': 'CE',
  'Belo Horizonte': 'MG',
  'Manaus': 'AM',
  'Curitiba': 'PR',
  'Recife': 'PE',
  'Porto Alegre': 'RS',
  'Goiânia': 'GO',
  'Belém': 'PA',
  'Maceió': 'AL',
  'Teresina': 'PI',
  'São Luís': 'MA',
  'Aracaju': 'SE',
  'Natal': 'RN',
  'Campo Grande': 'MS',
  'Cuiabá': 'MT',
  'João Pessoa': 'PB',
  'Boa Vista': 'RR',
  'Macapá': 'AP',
  'Palmas': 'TO',
  'Rio Branco': 'AC'
};

const ROUTES = {
  'São Paulo-Rio de Janeiro': 429,
  'Rio de Janeiro-São Paulo': 429,
  'São Paulo-Brasília': 1034,
  'Brasília-São Paulo': 1034,
  'São Paulo-Salvador': 2176,
  'Salvador-São Paulo': 2176,
  'Rio de Janeiro-Brasília': 1158,
  'Brasília-Rio de Janeiro': 1158,
  'São Paulo-Belo Horizonte': 586,
  'Belo Horizonte-São Paulo': 586,
  'Rio de Janeiro-Salvador': 1738,
  'Salvador-Rio de Janeiro': 1738,
  'São Paulo-Fortaleza': 2864,
  'Fortaleza-São Paulo': 2864,
  'Rio de Janeiro-Manaus': 3855,
  'Manaus-Rio de Janeiro': 3855,
  'São Paulo-Curitiba': 408,
  'Curitiba-São Paulo': 408,
  'São Paulo-Recife': 2325,
  'Recife-São Paulo': 2325,
  'Rio de Janeiro-Porto Alegre': 2297,
  'Porto Alegre-Rio de Janeiro': 2297,
  'Brasília-Goiânia': 209,
  'Goiânia-Brasília': 209,
  'Belém-Manaus': 1615,
  'Manaus-Belém': 1615,
  'Salvador-Maceió': 262,
  'Maceió-Salvador': 262,
  'Fortaleza-Recife': 701,
  'Recife-Fortaleza': 701,
  'Recife-Maceió': 254,
  'Maceió-Recife': 254,
  'Fortaleza-Teresina': 548,
  'Teresina-Fortaleza': 548,
  'Teresina-São Luís': 387,
  'São Luís-Teresina': 387,
  'Recife-João Pessoa': 120,
  'João Pessoa-Recife': 120,
  'Salvador-Aracaju': 355,
  'Aracaju-Salvador': 355,
  'Aracaju-Maceió': 270,
  'Maceió-Aracaju': 270,
  'Recife-Natal': 305,
  'Natal-Recife': 305,
  'Belo Horizonte-Brasília': 741,
  'Brasília-Belo Horizonte': 741,
  'Rio de Janeiro-Belo Horizonte': 586,
  'Belo Horizonte-Rio de Janeiro': 586,
  'Curitiba-Porto Alegre': 710,
  'Porto Alegre-Curitiba': 710,
  'São Paulo-Goiânia': 933,
  'Goiânia-São Paulo': 933,
  'Brasília-Cuiabá': 925,
  'Cuiabá-Brasília': 925,
  'Cuiabá-Campo Grande': 698,
  'Campo Grande-Cuiabá': 698,
  'Manaus-Boa Vista': 809,
  'Boa Vista-Manaus': 809,
  'Macapá-Belém': 651,
  'Belém-Macapá': 651,
  'Palmas-Goiânia': 792,
  'Goiânia-Palmas': 792,
  'Rio Branco-Manaus': 1409,
  'Manaus-Rio Branco': 1409,
  'Porto Alegre-São Paulo': 1403,
  'São Paulo-Porto Alegre': 1403
};

function getDistance(origin, destination) {
  const key1 = `${origin}-${destination}`;
  const key2 = `${destination}-${origin}`;
  
  if (ROUTES[key1]) return ROUTES[key1];
  if (ROUTES[key2]) return ROUTES[key2];
  
  return null;
}